MVCPHONECRUD/Models/Phone.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPHONECRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneId { get; set; }
        public string Model { get; set; }
        public string Company { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}

MVCPHONECRUD/Controllers/PhoneController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MVCPHONECRUD.Models;
using System.Linq.Dynamic;

namespace MVCPHONECRUD.Controllers
{
    public class PhoneController : Controller
    {
        private TestDbEntities db = new TestDbEntities();

        // GET: /Phone/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List(string filter = null, int page = 1,
         int pageSize = 5, string sort = "PhoneId", string sortdir = "DESC")
        {
            var records = new PagedList<Phone>();


            ViewBag.Sort = sort;
            ViewBag.SortDir = sortdir;
            ViewBag.Filter = filter;

            records.Content = db.Phone.Where(x => filter == null || (x.Model.Contains(filter)) || x.Company.Contains(filter))
                        .OrderBy(sort + " " + sortdir)
                        .Skip((page - 1) * pageSize)
                        .Take(pageSize)
                        .ToList();

            records.TotalRecords = db.Phone.Count(x => filter == null ||
                                                        (x.Model.Contains(filter)) || x.Company.Contains(filter));

            records.CurrentPage = page;
            records.PageSize = pageSize;


            return PartialView("_List", records);
        }


        public ActionResult Details(int id = 0)
        {
            Phone phone = db.Phone.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return PartialView("Details", phone);
        }


        // GET: /Phone/Create
        [HttpGet]
        public ActionResult Create()
        {
            var phone = new Phone();
            return PartialView("Create", phone);
        }


        // POST: /Phone/Create
        [HttpPost]
        public ActionResult Create(Phone phone)
        {
            if (ModelState.IsValid)
            {
                db.Phone.Add(phone);
                db.SaveChanges();
                return RedirectToAction("List");
                //  return Json(new { success = true });
            }
            return RedirectToAction("List");
        }


        // GET: /Phone/Edit/5
        [HttpGet]
        public ActionResult Edit(int id = 0)
        {
            var phone = db.Phone.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }

            return PartialView("Edit", phone);
        }


        // POST: /Phone/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Phone phone)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(phone).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("List");
                    return Json(new { success = true });
                }
                // throw new HttpException(404, "Not Found");
                return Json(new { status = 1 });
                //   return Json(new {status=1},JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {

                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                Response.StatusCode = 400;
                return Json(new { status = 2 });
            }

        }

        //
        // GET: /Phone/Delete/5
        public ActionResult Delete(int id = 0)
        {
            Phone phone = db.Phone.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", phone);
        }


        //
        // POST: /Phone/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var phone = db.Phone.Find(id);
            db.Phone.Remove(phone);
            db.SaveChanges();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCPHONECRUD/Views/Phone/Create.cshtml
@model MVCPHONECRUD.Models.Phone

@using (Ajax.BeginForm("Create", "Phone", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnSuccess = "updateSuccess", OnFailure = "updateFailure", UpdateTargetId = "partialChange", LoadingElementId = "Loading" }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => Model.Model, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(m => m.Model, new { @class = "form-control required" })
                <div>
                    @Html.ValidationMessageFor(m => m.Model)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => Model.Company, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(m => m.Company, new { @class = "form-control required" })
                <div>
                    @Html.ValidationMessageFor(m => m.Company)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => Model.Price, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(m => m.Price, new { @class = "form-control required" })
                <div>
                    @Html.ValidationMessageFor(m => m.Price)
                </div>
            </div>
        </div>

        <div class="form-group">

            <div class="col-sm-9 pull-right">
                <input class="btn btn-primary" type="submit" value="Save" />
                <button class="btn btn-warning" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>



}
<script>

    function updateSuccess(data) {

        $('#myModal').modal('hide');

        //window.location.href = '@Url.Action("Index", "Phone")';

    }
    function updateFailure(data) {

        alert('Error');

    }
</script>

MVCPHONECRUD/Views/Phone/Edit.cshtml
@model MVCPHONECRUD.Models.Phone

@using (Ajax.BeginForm("Edit", "Phone", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", OnSuccess = "updateSuccess", OnFailure = "updateFailure", UpdateTargetId = "partialChange", LoadingElementId = "Loading" }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.PhoneId)



    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(m => Model.Model, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(m => m.Model, new { @class = "form-control required" })
                <div>
                    @Html.ValidationMessageFor(m => m.Model)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => Model.Company, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(m => m.Company, new { @class = "form-control required" })
                <div>
                    @Html.ValidationMessageFor(m => m.Company)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => Model.Price, new { @class = "control-label col-sm-3" })
            <div class="col-sm-9">
                @Html.TextBoxFor(m => m.Price, new { @class = "form-control required" })
                <div>
                    @Html.ValidationMessageFor(m => m.Price)
                </div>
            </div>
        </div>

        <div class="form-group">

            <div class="col-sm-9 pull-right">
                <input class="btn btn-primary" type="submit" value="Save" />
                <button class="btn btn-warning" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>


}

<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="myModalContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Phone</h4>
            </div>
            <div class="modal-body" id="modalBody1">

            </div>

        </div>
    </div>
</div>
<script>

    function updateSuccess(data) {

        $('#myModal').modal('hide');

        //console.log(data);
        //if (data.status == 1) {
        //    alert('Error');
        //}

        if (data.status == 1) {

          //  $('#modalBody').html("Error");
            //  window.location.href = '@Url.Action("Index", "Phone")';
            console.log(data);
         //   }

            //$('#myModal1').modal('show');
        }
        //else {
        //   // $('#modalBody').html("Error");
        //    $('#myModal').modal('show');
        //}
        //window.location.href = '@Url.Action("Index", "Phone")';


    }
    function updateFailure(data) {
        console.log(data);
        //$('#modalBody').html("Error");
        $('#myModal').modal('hide');
        //$('#myModal').on('hidden', function() {
        //    // Load up a new modal...
        //    console.log('Hidden');
        //    $('#myModal1').modal('show');
        //});
        //$('#myModal').on('hidden.bs.modal', function(e) {
        //    $('#myModal1').modal('show');
        //});
        //alert('Error');
        //$('#myModal1').modal('show');
    }

    function complete(result) {
        //var isError = $('span.field-validation-error', result.responseText).length > 0;
        //if (isError) {
        //    // there was an error => we update the container of the form
        //    $('#frmContainer').html(result.responseText);
        //} else {
        //    // no error => we hide validation errors and update the result container
        //    $('#frm .field-validation-error').hide();
        //    $('#frm .input-validation-error').removeClass('input-validation-error');
        //    $('#result').html(result.responseText);
        //}
        console.log(result);
    }

</script>

MVCPHONECRUD/Views/Phone/Index.cshtml
@using System.Collections
@using MVCPHONECRUD.Models
@model MVCPHONECRUD.Models.PagedList<MVCPHONECRUD.Models.Phone>
@{
    ViewBag.Title = "Phone List";
}



<div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">
        My Table

    </div>

    <div id="partialChange">

    </div>


</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content" id="myModalContent">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Phone</h4>
            </div>
            <div class="modal-body" id="modalBody">

            </div>

        </div>
    </div>
</div>

@section Scripts{



    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script>

    $(function () {
        $.ajaxSetup({ cache: false });


        $.ajax({
            type: "GET",
            url: '@Url.Action("List","Phone")',
            contentType: "application/json; charset=utf-8",
            success: function (mydata) {
                $('#partialChange').html(mydata);

            },
            error: function (mydata) {
                alert(mydata + ' error');
            },
        });
        // return false;


    });



    </script>

}

MVCPHONECRUD/Views/Phone/_List.cshtml
@model MVCPHONECRUD.Models.PagedList<MVCPHONECRUD.Models.Phone>




<div class="panel-body">
    <div class="row">
        <div class="col-md-6">

            @using (Ajax.BeginForm("List", "Phone", FormMethod.Post, new AjaxOptions { InsertionMode = InsertionMode.Replace, HttpMethod = "POST", UpdateTargetId = "partialChange", LoadingElementId = "Loading" }, new { @class = "form-horizontal" }))
            {
                <div class="input-group col-md-6">
                    <input id="filter" class="form-control" type="text" name="filter">

                    <span class="input-group-btn ">
                        <input class="btn btn-default" type="submit" value="Search" />
                        <span class="glyphicon glyphicon-search"></span>

                    </span>
                </div>
            }

        </div>
        <div class="col-md-6">
            @*<div class="dropdown pull-right">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Dropdown
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="#">Action</a></li>
                    </ul>

                </div>*@
            <button class="btn btn-danger pull-right" id="crateBtn">+</button>
        </div>
    </div>
    <br />
    <!-- Table -->


    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%" style=" margin-bottom:0px">
        <thead>
            <tr>
                <th>

                    @*@Html.ActionLink(@Html.DisplayNameFor(model => Model.Content.First().Model).ToString(), "Index", "Phone", new { sort = "Model", sortdir = ViewBag.SortDir == "DESC" ? "ASC" : "DESC" }, new { @id = Model.Content.First().PhoneId })*@
                    @if (Model.Content.Count > 0)
                    {
                        @Ajax.ActionLink(@Html.DisplayNameFor(model => Model.Content.First().Model).ToString(), "List", "Phone", new { sort = "Model", sortdir = ViewBag.SortDir == "DESC" ? "ASC" : "DESC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace }, new { @id = Model.Content.First().PhoneId })
                    }
                    else
                    {
                        @Ajax.ActionLink("Model", "List", "Phone", new { sort = "Model", sortdir = ViewBag.SortDir == "DESC" ? "ASC" : "DESC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace })

                    }


                </th>
                <th>
                    @if (Model.Content.Count > 0)
                    {
                        @Ajax.ActionLink(@Html.DisplayNameFor(model => Model.Content.First().Company).ToString(), "List", "Phone", new { sort = "Company", sortdir = ViewBag.SortDir == "DESC" ? "ASC" : "DESC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace }, new { @id = Model.Content.First().PhoneId })
                    }
                    else
                    {
                        @Ajax.ActionLink("Company", "List", "Phone", new { sort = "Company", sortdir = ViewBag.SortDir == "DESC" ? "ASC" : "DESC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace })

                    }

                </th>
                <th>
                    @if (Model.Content.Count > 0)
                    {
                        @Ajax.ActionLink(@Html.DisplayNameFor(model => Model.Content.First().Price).ToString(), "List", "Phone", new { sort = "Price", sortdir = ViewBag.SortDir == "DESC" ? "ASC" : "DESC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace }, new { @id = Model.Content.First().PhoneId })
                    }
                    else
                    {
                        @Ajax.ActionLink("Price", "List", "Phone", new { sort = "Price", sortdir = ViewBag.SortDir == "DESC" ? "ASC" : "DESC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace })

                    }

                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model.Content)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Company)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @*@Html.ActionLink("Edit", "Edit", new { id = item.PhoneId }, new { @class = "btn btn-info editCls" }) |*@
                        <button type="button" class="btn btn-info editButton" value=@item.PhoneId>

                            Edit
                        </button>
                    </td>
                </tr>
            }

        </tbody>
    </table>

    <ul class="pagination" style="margin:0px;">

        <li>
            @*<a href="@Url.Action("List", "Another", new { page = Model.CurrentPage - 1 == 0 ? 1 : Model.CurrentPage - 1, sort = ViewBag.Sort, sortdir = ViewBag.SortDir == "DESC" ? "DESC" : "ASC" })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>*@
            @Ajax.ActionLink("Previous", "List", "Phone", new { page = Model.CurrentPage - 1 == 0 ? 1 : Model.CurrentPage - 1, sort = ViewBag.Sort, sortdir = ViewBag.SortDir == "DESC" ? "DESC" : "ASC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace })
        </li>
        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            @*<li><a href="@Url.Action("List", "Another", new { page = i, sort = ViewBag.Sort })">@i</a></li>*@
            <li>@Ajax.ActionLink(i.ToString(), "List", "Phone", new { page = i, sort = ViewBag.Sort }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace })</li>
        }
        <li>
            @*<a href="@Url.Action("List", "Another", new { page = Model.CurrentPage + 1 > Model.TotalPages ? Model.CurrentPage : Model.CurrentPage + 1, sort = ViewBag.Sort, sortdir = ViewBag.SortDir == "DESC" ? "DESC" : "ASC" })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>*@
            @Ajax.ActionLink("Next", "List", "Phone", new { page = Model.CurrentPage + 1 > Model.TotalPages ? Model.CurrentPage : Model.CurrentPage + 1, sort = ViewBag.Sort, sortdir = ViewBag.SortDir == "DESC" ? "DESC" : "ASC" }, new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "partialChange", InsertionMode = InsertionMode.Replace })


        </li>
    </ul>

</div>





<script>
    $(function () {
        $.ajaxSetup({ cache: false });
        $("#crateBtn").on("click", function (e) {

            $.ajax({
                type: "GET",
                url: '@Url.Action("Create","Phone")',
                contentType: "application/json; charset=utf-8",
                success: function (mydata) {
                    $('#modalBody').html(mydata);
                    $('#myModal').modal('show');
                },
                error: function (mydata) {
                    alert(mydata + ' error');
                },
            });
            return false;
        });

    });
    $(function () {
        $.ajaxSetup({ cache: false });
        $(".editButton").on("click", function (e) {
            // alert($(this).val());
            var phoneId = $(this).val();
            var page=@Model.CurrentPage;
            alert(page);
            $.ajax({
                type: "GET",
                url: '@Url.Action("Edit","Phone")',
                data: { id: phoneId},
                // data: JSON.stringify({id: phoneId}),
                contentType: "application/json; charset=utf-8",
                success: function (mydata) {
                    $('#modalBody').html(mydata);
                    $('#myModal').modal('show');
                },
                error: function (mydata) {
                    alert(mydata + ' error');
                },
            });
            return false;
        });


    });


</script>